### ISSUE TITLE
part size issue in BOM

### ISSUE THREAD

**Issue by extremenerble** [benjiaomodular/MiniSNH#1]
I believe the part # you have in your BOM is for an 0805 sized cap, and the pads are certainly the same sized as all of your other 0603 parts.

Line 1, part # CC0805KRX7R9BB104 - 100nf cap.
![Screen Shot 2023-08-11 at 7 50 53 PM](https://github.com/benjiaomodular/MiniSNH/assets/142069656/d9b6582e-51c2-4234-9247-e3d626fcaae8)

**Comment by extremenerble** [comment]
Ah, here's a quick fix. This is the 0603 version part # [CC0603JPX7R9BB103](https://www.mouser.com/ProductDetail/YAGEO/CC0603JPX7R9BB103?qs=AgBp2OyFlx8sWsQrSGxfow%3D%3D)

**Comment by extremenerble** [comment]
Here's an alternative 0603 part [CC0603KPX7R9BB104](https://www.mouser.com/ProductDetail/YAGEO/CC0603KPX7R9BB104?qs=7s%252B3O6pAiyBs9nC6A1iRAA%3D%3D)

**Comment by extremenerble** [comment]
Also you're missing a part # for the 2.2k resistor. Here's a possibility

[RC0603FR-072K2L](https://www.mouser.com/ProductDetail/YAGEO/RC0603FR-072K2L?qs=diQw95jMAeOQmNpe2MM%252BPw%3D%3D)

**Comment by benjiao** [comment]
Hey thanks for bringing it up! Here's are the part numbers that I use:

- CC0603JRX7R9BB104
- RK73B1JTTD222J

**Comment by benjiao** [comment]
Updated the BOM! Also added the 33k resistor and 100k trimmer.

https://benjiaomodular.com/boms/MiniSNH%20-%20v1.1.html
